# Generated by Django 2.2.12 on 2020-04-11 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=150, null=True)),
                ('title', models.CharField(max_length=150, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('genre', models.CharField(choices=[('action', 'Action'), ('novel', 'Novel'), ('fiction', 'Fiction')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/book_images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='books.Book')),
            ],
            options={
                'verbose_name_plural': 'BookImages',
            },
        ),
    ]
